services:
  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
  
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      
volumes:
  db:
